export interface RegionDef {
  slug: string;
  name: string;
  country_code: string;
  country_name: string;
  geojson_id: string;
  description: string;
  landscape_type: string[];
  activities: string[];
  cuisine_tags: string[];
  centroid_lat: number;
  centroid_lon: number;
  is_coastal: boolean;
}

export const REGIONS: RegionDef[] = [
  // ─── Philippines (5) ───────────────────────────────────────────────
  {
    slug: 'ph-palawan',
    name: 'Palawan',
    country_code: 'PH',
    country_name: 'Philippines',
    geojson_id: 'ph-palawan',
    description:
      'A long, narrow island with towering limestone karsts, underground rivers, and some of the clearest water in Southeast Asia. El Nido and Coron offer world-class island-hopping and wreck diving.',
    landscape_type: ['island', 'beach', 'jungle'],
    activities: ['diving', 'snorkeling', 'kayaking', 'beach', 'wildlife', 'photography'],
    cuisine_tags: ['filipino'],
    centroid_lat: 10.0,
    centroid_lon: 118.9,
    is_coastal: true,
  },
  {
    slug: 'ph-cebu-bohol',
    name: 'Cebu & Bohol',
    country_code: 'PH',
    country_name: 'Philippines',
    geojson_id: 'ph-cebu-bohol',
    description:
      'Twin island provinces famous for whale shark encounters in Oslob, the Chocolate Hills of Bohol, and tarsier sanctuaries. Cebu City serves as a vibrant gateway to the Visayas.',
    landscape_type: ['island', 'beach', 'jungle'],
    activities: ['diving', 'snorkeling', 'wildlife', 'cultural', 'beach', 'adventure'],
    cuisine_tags: ['filipino'],
    centroid_lat: 9.85,
    centroid_lon: 124.0,
    is_coastal: true,
  },
  {
    slug: 'ph-siargao',
    name: 'Siargao',
    country_code: 'PH',
    country_name: 'Philippines',
    geojson_id: 'ph-siargao',
    description:
      'Known as the surfing capital of the Philippines, this teardrop-shaped island draws wave riders to Cloud 9 and offers mangrove-fringed lagoons, rock pools, and a laid-back island vibe.',
    landscape_type: ['island', 'beach', 'jungle'],
    activities: ['surfing', 'beach', 'snorkeling', 'kayaking', 'nightlife'],
    cuisine_tags: ['filipino'],
    centroid_lat: 9.86,
    centroid_lon: 126.05,
    is_coastal: true,
  },
  {
    slug: 'ph-batanes',
    name: 'Batanes Islands',
    country_code: 'PH',
    country_name: 'Philippines',
    geojson_id: 'ph-batanes',
    description:
      'The northernmost province of the Philippines, where rolling green hills meet dramatic cliffs above the Pacific. Ivatan stone houses and a culture shaped by typhoons make Batanes unlike anywhere else in the country.',
    landscape_type: ['island', 'countryside', 'mountain'],
    activities: ['hiking', 'cycling', 'photography', 'cultural'],
    cuisine_tags: ['filipino'],
    centroid_lat: 20.45,
    centroid_lon: 121.97,
    is_coastal: true,
  },
  {
    slug: 'ph-mindanao-highlands',
    name: 'Mindanao Highlands',
    country_code: 'PH',
    country_name: 'Philippines',
    geojson_id: 'ph-mindanao-highlands',
    description:
      'Home to Mt. Apo, the Philippines\' highest peak, and the ancestral lands of indigenous Lumad communities. The cool-climate highlands around Bukidnon and Davao offer pineapple plantations and white-water rapids.',
    landscape_type: ['mountain', 'jungle'],
    activities: ['hiking', 'adventure', 'cultural', 'wildlife', 'climbing'],
    cuisine_tags: ['filipino'],
    centroid_lat: 7.5,
    centroid_lon: 125.5,
    is_coastal: false,
  },

  // ─── China (6) ─────────────────────────────────────────────────────
  {
    slug: 'cn-yunnan',
    name: 'Yunnan',
    country_code: 'CN',
    country_name: 'China',
    geojson_id: 'cn-yunnan',
    description:
      'A province of staggering ethnic and geographic diversity, from the Tiger Leaping Gorge to the terraced rice paddies of Yuanyang. Ancient towns like Lijiang and Dali sit at the crossroads of Tibetan, Bai, and Naxi cultures.',
    landscape_type: ['mountain', 'countryside', 'jungle'],
    activities: ['hiking', 'cultural', 'photography', 'cycling', 'food'],
    cuisine_tags: ['chinese'],
    centroid_lat: 25.05,
    centroid_lon: 101.5,
    is_coastal: false,
  },
  {
    slug: 'cn-guilin-guangxi',
    name: 'Guilin & Guangxi',
    country_code: 'CN',
    country_name: 'China',
    geojson_id: 'cn-guilin-guangxi',
    description:
      'Karst towers rise from emerald rice paddies along the Li River, creating the landscapes that inspired centuries of Chinese scroll painting. Yangshuo is a base for cycling, rock climbing, and bamboo-raft drifting.',
    landscape_type: ['river', 'mountain', 'countryside'],
    activities: ['cycling', 'climbing', 'kayaking', 'photography', 'cultural'],
    cuisine_tags: ['chinese'],
    centroid_lat: 24.8,
    centroid_lon: 110.3,
    is_coastal: false,
  },
  {
    slug: 'cn-sichuan',
    name: 'Sichuan',
    country_code: 'CN',
    country_name: 'China',
    geojson_id: 'cn-sichuan',
    description:
      'Fiery cuisine and giant pandas headline a province that stretches from the misty Chengdu basin to the snow-capped peaks bordering Tibet. Jiuzhaigou\'s turquoise lakes and the Leshan Giant Buddha are among China\'s most iconic sights.',
    landscape_type: ['mountain', 'countryside'],
    activities: ['hiking', 'wildlife', 'food', 'cultural', 'photography'],
    cuisine_tags: ['chinese'],
    centroid_lat: 30.65,
    centroid_lon: 104.06,
    is_coastal: false,
  },
  {
    slug: 'cn-xinjiang',
    name: 'Xinjiang',
    country_code: 'CN',
    country_name: 'China',
    geojson_id: 'cn-xinjiang',
    description:
      'China\'s vast northwestern frontier blends Central Asian bazaars, the Taklamakan Desert, and the snow-capped Tian Shan. Kashgar\'s Sunday market and the Karakoram Highway offer experiences far removed from eastern China.',
    landscape_type: ['desert', 'mountain'],
    activities: ['hiking', 'cultural', 'photography', 'adventure', 'cycling'],
    cuisine_tags: ['chinese'],
    centroid_lat: 41.0,
    centroid_lon: 85.0,
    is_coastal: false,
  },
  {
    slug: 'cn-hainan',
    name: 'Hainan Island',
    country_code: 'CN',
    country_name: 'China',
    geojson_id: 'cn-hainan',
    description:
      'China\'s tropical island province at the southern tip of the country, with palm-lined beaches around Sanya and dense rainforest in the interior. Often called the "Hawaii of China" for its resort culture and warm year-round climate.',
    landscape_type: ['island', 'beach', 'jungle'],
    activities: ['beach', 'surfing', 'snorkeling', 'diving', 'food'],
    cuisine_tags: ['chinese'],
    centroid_lat: 19.2,
    centroid_lon: 109.75,
    is_coastal: true,
  },
  {
    slug: 'cn-beijing-north',
    name: 'Beijing & North',
    country_code: 'CN',
    country_name: 'China',
    geojson_id: 'cn-beijing-north',
    description:
      'The imperial capital anchors a region that includes the Great Wall, Ming tombs, and the vast grasslands of Inner Mongolia. Beijing itself layers ancient hutong alleys with contemporary art districts and world-class street food.',
    landscape_type: ['city', 'mountain', 'countryside'],
    activities: ['cultural', 'food', 'hiking', 'photography', 'nightlife'],
    cuisine_tags: ['chinese'],
    centroid_lat: 39.9,
    centroid_lon: 116.4,
    is_coastal: false,
  },

  // ─── Thailand (4) ──────────────────────────────────────────────────
  {
    slug: 'th-chiang-mai-north',
    name: 'Chiang Mai & North',
    country_code: 'TH',
    country_name: 'Thailand',
    geojson_id: 'th-chiang-mai-north',
    description:
      'Mist-wrapped mountains, hill-tribe villages, and over 300 temples define northern Thailand. Chiang Mai\'s Night Bazaar, cooking classes, and proximity to Doi Inthanon make it the cultural heart of the north.',
    landscape_type: ['mountain', 'jungle', 'countryside'],
    activities: ['cultural', 'food', 'hiking', 'cycling', 'photography'],
    cuisine_tags: ['thai'],
    centroid_lat: 18.8,
    centroid_lon: 98.98,
    is_coastal: false,
  },
  {
    slug: 'th-bangkok-central',
    name: 'Bangkok & Central',
    country_code: 'TH',
    country_name: 'Thailand',
    geojson_id: 'th-bangkok-central',
    description:
      'A frenetic capital where golden temple spires sit beside neon-lit skyscrapers, and floating markets coexist with rooftop bars. The central plains beyond the city hold ancient Ayutthaya and Kanchanaburi\'s wartime history.',
    landscape_type: ['city', 'river'],
    activities: ['food', 'cultural', 'nightlife', 'photography'],
    cuisine_tags: ['thai'],
    centroid_lat: 13.75,
    centroid_lon: 100.5,
    is_coastal: false,
  },
  {
    slug: 'th-gulf-coast',
    name: 'Gulf Coast',
    country_code: 'TH',
    country_name: 'Thailand',
    geojson_id: 'th-gulf-coast',
    description:
      'Ko Samui, Ko Pha-ngan, and Ko Tao line the Gulf of Thailand, each with a distinct character: luxury resorts, full-moon parties, and world-renowned dive sites respectively. The coastline around Chumphon offers quieter alternatives.',
    landscape_type: ['island', 'beach'],
    activities: ['diving', 'snorkeling', 'beach', 'nightlife', 'surfing'],
    cuisine_tags: ['thai'],
    centroid_lat: 9.5,
    centroid_lon: 100.07,
    is_coastal: true,
  },
  {
    slug: 'th-andaman-coast',
    name: 'Andaman Coast',
    country_code: 'TH',
    country_name: 'Thailand',
    geojson_id: 'th-andaman-coast',
    description:
      'Dramatic limestone sea stacks rise from turquoise Andaman waters around Phuket, Krabi, and the Phi Phi Islands. Quieter spots like Khao Lak and Ko Lanta balance the busy resort strips with national-park reefs and mangroves.',
    landscape_type: ['beach', 'island', 'jungle'],
    activities: ['diving', 'snorkeling', 'beach', 'kayaking', 'climbing', 'photography'],
    cuisine_tags: ['thai'],
    centroid_lat: 8.0,
    centroid_lon: 98.3,
    is_coastal: true,
  },

  // ─── Vietnam (6) ───────────────────────────────────────────────────
  {
    slug: 'vn-hanoi-delta',
    name: 'Hanoi & Delta',
    country_code: 'VN',
    country_name: 'Vietnam',
    geojson_id: 'vn-hanoi-delta',
    description:
      'Vietnam\'s thousand-year-old capital combines French colonial boulevards, incense-filled temples, and the world\'s best pho. Nearby Ha Long Bay and Ninh Binh ("Ha Long on land") anchor the Red River Delta region.',
    landscape_type: ['city', 'river', 'countryside'],
    activities: ['food', 'cultural', 'kayaking', 'photography', 'cycling'],
    cuisine_tags: ['vietnamese'],
    centroid_lat: 21.03,
    centroid_lon: 105.85,
    is_coastal: false,
  },
  {
    slug: 'vn-sapa-highlands',
    name: 'Sa Pa & Highlands',
    country_code: 'VN',
    country_name: 'Vietnam',
    geojson_id: 'vn-sapa-highlands',
    description:
      'Terraced rice paddies cascade down the slopes of the Hoang Lien Son range, home to Fansipan, Indochina\'s highest peak. Hmong and Dao villages offer homestays amid some of Southeast Asia\'s most dramatic highland scenery.',
    landscape_type: ['mountain', 'countryside'],
    activities: ['hiking', 'cultural', 'photography', 'cycling'],
    cuisine_tags: ['vietnamese'],
    centroid_lat: 22.34,
    centroid_lon: 103.84,
    is_coastal: false,
  },
  {
    slug: 'vn-da-nang',
    name: 'Da Nang',
    country_code: 'VN',
    country_name: 'Vietnam',
    geojson_id: 'vn-da-nang',
    description:
      'A fast-growing coastal city with a long sandy beach, the Marble Mountains, and the Golden Bridge in the Ba Na Hills. Da Nang serves as a modern base for exploring central Vietnam\'s imperial and wartime history.',
    landscape_type: ['beach', 'city', 'mountain'],
    activities: ['beach', 'surfing', 'cultural', 'food', 'nightlife'],
    cuisine_tags: ['vietnamese'],
    centroid_lat: 16.05,
    centroid_lon: 108.2,
    is_coastal: true,
  },
  {
    slug: 'vn-hoi-an',
    name: 'Hoi An',
    country_code: 'VN',
    country_name: 'Vietnam',
    geojson_id: 'vn-hoi-an',
    description:
      'A UNESCO-listed trading port where lantern-lit streets reflect in the Thu Bon River. Famous for its tailors, cooking classes, and An Bang Beach, Hoi An is one of Vietnam\'s most atmospheric small towns.',
    landscape_type: ['city', 'beach', 'river'],
    activities: ['cultural', 'food', 'cycling', 'beach', 'photography'],
    cuisine_tags: ['vietnamese'],
    centroid_lat: 15.88,
    centroid_lon: 108.33,
    is_coastal: true,
  },
  {
    slug: 'vn-ho-chi-minh',
    name: 'Ho Chi Minh City',
    country_code: 'VN',
    country_name: 'Vietnam',
    geojson_id: 'vn-ho-chi-minh',
    description:
      'Vietnam\'s largest city pulses with motorbike traffic, rooftop bars, and some of the country\'s best street food. The Cu Chi Tunnels and Mekong Delta day trips add historical and rural dimensions to the urban experience.',
    landscape_type: ['city', 'river'],
    activities: ['food', 'cultural', 'nightlife', 'photography'],
    cuisine_tags: ['vietnamese'],
    centroid_lat: 10.82,
    centroid_lon: 106.63,
    is_coastal: false,
  },
  {
    slug: 'vn-phu-quoc',
    name: 'Phu Quoc',
    country_code: 'VN',
    country_name: 'Vietnam',
    geojson_id: 'vn-phu-quoc',
    description:
      'Vietnam\'s largest island sits in the Gulf of Thailand, ringed by white-sand beaches and coral reefs. Fish-sauce factories, pepper plantations, and a national park covering half the island give it character beyond the resorts.',
    landscape_type: ['island', 'beach', 'jungle'],
    activities: ['beach', 'snorkeling', 'diving', 'kayaking', 'food'],
    cuisine_tags: ['vietnamese'],
    centroid_lat: 10.23,
    centroid_lon: 103.96,
    is_coastal: true,
  },

  // ─── Indonesia (6) ─────────────────────────────────────────────────
  {
    slug: 'id-bali',
    name: 'Bali',
    country_code: 'ID',
    country_name: 'Indonesia',
    geojson_id: 'id-bali',
    description:
      'An island of terraced rice paddies, volcanic peaks, and Hindu temples perched on sea cliffs. Ubud\'s art scene, Seminyak\'s beach clubs, and Uluwatu\'s surf breaks make Bali Indonesia\'s most visited destination.',
    landscape_type: ['island', 'beach', 'mountain', 'jungle'],
    activities: ['surfing', 'cultural', 'food', 'diving', 'yoga', 'nightlife', 'photography'],
    cuisine_tags: ['indonesian'],
    centroid_lat: -8.35,
    centroid_lon: 115.17,
    is_coastal: true,
  },
  {
    slug: 'id-lombok-gili',
    name: 'Lombok & Gili',
    country_code: 'ID',
    country_name: 'Indonesia',
    geojson_id: 'id-lombok-gili',
    description:
      'Lombok offers Mt. Rinjani\'s volcanic caldera trek and quieter beaches than its neighbor Bali. The three Gili islands -- Trawangan, Air, and Meno -- are car-free specks known for turtle snorkeling and sunset bars.',
    landscape_type: ['island', 'beach', 'mountain'],
    activities: ['hiking', 'snorkeling', 'diving', 'surfing', 'beach'],
    cuisine_tags: ['indonesian'],
    centroid_lat: -8.56,
    centroid_lon: 116.35,
    is_coastal: true,
  },
  {
    slug: 'id-east-java',
    name: 'East Java',
    country_code: 'ID',
    country_name: 'Indonesia',
    geojson_id: 'id-east-java',
    description:
      'Sunrise over the otherworldly caldera of Mt. Bromo and the electric-blue flames of Ijen crater define East Java. Beyond the volcanoes, the region holds Surabaya\'s Arab Quarter and the forested slopes of Arjuno-Welirang.',
    landscape_type: ['mountain', 'jungle'],
    activities: ['hiking', 'photography', 'adventure', 'cultural'],
    cuisine_tags: ['indonesian'],
    centroid_lat: -7.95,
    centroid_lon: 112.95,
    is_coastal: false,
  },
  {
    slug: 'id-raja-ampat',
    name: 'Raja Ampat',
    country_code: 'ID',
    country_name: 'Indonesia',
    geojson_id: 'id-raja-ampat',
    description:
      'A remote archipelago off West Papua harboring the highest marine biodiversity on Earth. Over 1,500 fish species and 75% of all known coral species make Raja Ampat the holy grail for divers and marine biologists.',
    landscape_type: ['island', 'jungle'],
    activities: ['diving', 'snorkeling', 'kayaking', 'wildlife', 'photography'],
    cuisine_tags: ['indonesian'],
    centroid_lat: -1.0,
    centroid_lon: 130.5,
    is_coastal: true,
  },
  {
    slug: 'id-komodo-flores',
    name: 'Komodo & Flores',
    country_code: 'ID',
    country_name: 'Indonesia',
    geojson_id: 'id-komodo-flores',
    description:
      'Komodo dragons roam freely on their namesake islands, while nearby Flores offers the tri-colored crater lakes of Kelimutu and traditional Ngada villages. Pink Beach and Padar viewpoint are among Indonesia\'s most photogenic spots.',
    landscape_type: ['island', 'mountain', 'beach'],
    activities: ['diving', 'hiking', 'wildlife', 'snorkeling', 'photography'],
    cuisine_tags: ['indonesian'],
    centroid_lat: -8.55,
    centroid_lon: 120.5,
    is_coastal: true,
  },
  {
    slug: 'id-sulawesi-togean',
    name: 'Sulawesi (Togean)',
    country_code: 'ID',
    country_name: 'Indonesia',
    geojson_id: 'id-sulawesi-togean',
    description:
      'The Togean Islands in Central Sulawesi remain one of Indonesia\'s least-visited reef systems, with Bajau sea-nomad stilt villages and jellyfish lakes. Mainland Tana Toraja\'s elaborate funeral rites are among Southeast Asia\'s most remarkable cultural experiences.',
    landscape_type: ['island', 'jungle'],
    activities: ['diving', 'snorkeling', 'cultural', 'wildlife', 'kayaking'],
    cuisine_tags: ['indonesian'],
    centroid_lat: -0.4,
    centroid_lon: 121.9,
    is_coastal: true,
  },

  // ─── Malaysia (7) ──────────────────────────────────────────────────
  {
    slug: 'my-kl-west-coast',
    name: 'KL & West Coast',
    country_code: 'MY',
    country_name: 'Malaysia',
    geojson_id: 'my-kl-west-coast',
    description:
      'Kuala Lumpur\'s Petronas Towers crown a city where Malay, Chinese, and Indian cultures converge over spectacular hawker food. The Batu Caves and Malacca\'s Peranakan heritage are easy day trips from the capital.',
    landscape_type: ['city'],
    activities: ['food', 'cultural', 'nightlife', 'photography'],
    cuisine_tags: ['malaysian'],
    centroid_lat: 3.14,
    centroid_lon: 101.69,
    is_coastal: false,
  },
  {
    slug: 'my-penang',
    name: 'Penang',
    country_code: 'MY',
    country_name: 'Malaysia',
    geojson_id: 'my-penang',
    description:
      'George Town\'s UNESCO-listed streets mix colonial architecture with Chinese clan houses and street-art murals. Widely regarded as Malaysia\'s food capital, Penang\'s hawker stalls serve char kway teow and assam laksa that draw visitors from around the world.',
    landscape_type: ['island', 'city'],
    activities: ['food', 'cultural', 'photography', 'cycling', 'beach'],
    cuisine_tags: ['malaysian'],
    centroid_lat: 5.41,
    centroid_lon: 100.33,
    is_coastal: true,
  },
  {
    slug: 'my-langkawi',
    name: 'Langkawi',
    country_code: 'MY',
    country_name: 'Malaysia',
    geojson_id: 'my-langkawi',
    description:
      'A duty-free archipelago of 99 islands off Malaysia\'s northwest coast, known for its SkyBridge, mangrove boat tours, and UNESCO Global Geopark status. Langkawi combines resort-style beaches with genuinely wild jungle interior.',
    landscape_type: ['island', 'beach', 'jungle'],
    activities: ['beach', 'kayaking', 'snorkeling', 'wildlife', 'photography'],
    cuisine_tags: ['malaysian'],
    centroid_lat: 6.35,
    centroid_lon: 99.8,
    is_coastal: true,
  },
  {
    slug: 'my-cameron-highlands',
    name: 'Cameron Highlands',
    country_code: 'MY',
    country_name: 'Malaysia',
    geojson_id: 'my-cameron-highlands',
    description:
      'Cool-climate tea plantations, strawberry farms, and mossy cloud forest blanket these highlands established as a British colonial hill station. The BOH tea estate and the Mossy Forest boardwalk are signature experiences.',
    landscape_type: ['mountain', 'countryside'],
    activities: ['hiking', 'photography', 'food'],
    cuisine_tags: ['malaysian'],
    centroid_lat: 4.47,
    centroid_lon: 101.38,
    is_coastal: false,
  },
  {
    slug: 'my-perhentian-east',
    name: 'Perhentian & East Coast',
    country_code: 'MY',
    country_name: 'Malaysia',
    geojson_id: 'my-perhentian-east',
    description:
      'The Perhentian Islands and nearby Redang and Lang Tengah offer clear-water snorkeling and budget-friendly beach huts on Peninsular Malaysia\'s quieter eastern shore. Sea turtle nesting sites dot the coastline from Cherating to Terengganu.',
    landscape_type: ['island', 'beach'],
    activities: ['snorkeling', 'diving', 'beach', 'wildlife'],
    cuisine_tags: ['malaysian'],
    centroid_lat: 5.9,
    centroid_lon: 102.75,
    is_coastal: true,
  },
  {
    slug: 'my-borneo-sabah',
    name: 'Borneo Sabah',
    country_code: 'MY',
    country_name: 'Malaysia',
    geojson_id: 'my-borneo-sabah',
    description:
      'Sabah is home to Mt. Kinabalu, Southeast Asia\'s highest peak, and the orangutan rehabilitation centres of Sepilok. The Danum Valley and Kinabatangan River rank among the best places on Earth to spot pygmy elephants, proboscis monkeys, and hornbills.',
    landscape_type: ['jungle', 'mountain', 'island'],
    activities: ['wildlife', 'hiking', 'diving', 'climbing', 'photography'],
    cuisine_tags: ['malaysian'],
    centroid_lat: 5.98,
    centroid_lon: 116.07,
    is_coastal: true,
  },
  {
    slug: 'my-borneo-sarawak',
    name: 'Borneo Sarawak',
    country_code: 'MY',
    country_name: 'Malaysia',
    geojson_id: 'my-borneo-sarawak',
    description:
      'Sarawak\'s vast cave systems at Mulu National Park and the longhouse cultures of the Iban people define Malaysian Borneo\'s larger state. Kuching, the charming waterfront capital, is a gateway to orangutan sanctuaries and Bako National Park\'s coastal jungle trails.',
    landscape_type: ['jungle', 'river', 'mountain'],
    activities: ['wildlife', 'hiking', 'cultural', 'kayaking', 'adventure'],
    cuisine_tags: ['malaysian'],
    centroid_lat: 2.5,
    centroid_lon: 111.0,
    is_coastal: true,
  },

  // ─── Japan (6) ─────────────────────────────────────────────────────
  {
    slug: 'jp-tokyo-kanto',
    name: 'Tokyo & Kanto',
    country_code: 'JP',
    country_name: 'Japan',
    geojson_id: 'jp-tokyo-kanto',
    description:
      'The world\'s largest metro area layers ancient shrines beneath neon skyscrapers, with Tsukiji\'s seafood, Harajuku\'s fashion, and Akihabara\'s electronics packed into distinct neighborhoods. Day trips to Kamakura, Nikko, and Mt. Fuji viewpoints extend the region.',
    landscape_type: ['city', 'mountain'],
    activities: ['food', 'cultural', 'nightlife', 'photography'],
    cuisine_tags: ['japanese'],
    centroid_lat: 35.68,
    centroid_lon: 139.69,
    is_coastal: true,
  },
  {
    slug: 'jp-kyoto-kansai',
    name: 'Kyoto & Kansai',
    country_code: 'JP',
    country_name: 'Japan',
    geojson_id: 'jp-kyoto-kansai',
    description:
      'Japan\'s cultural heartland, where over 2,000 temples and shrines share the stage with Osaka\'s street-food alleys and Nara\'s free-roaming deer. Kyoto\'s geisha district, bamboo groves, and tea ceremonies define traditional Japan.',
    landscape_type: ['city', 'mountain', 'countryside'],
    activities: ['cultural', 'food', 'hiking', 'photography', 'cycling'],
    cuisine_tags: ['japanese'],
    centroid_lat: 35.01,
    centroid_lon: 135.77,
    is_coastal: true,
  },
  {
    slug: 'jp-hokkaido',
    name: 'Hokkaido',
    country_code: 'JP',
    country_name: 'Japan',
    geojson_id: 'jp-hokkaido',
    description:
      'Japan\'s northernmost island delivers world-class powder skiing in Niseko, lavender fields in Furano, and the volcanic caldera lakes of Akan and Shikotsu. Sapporo\'s beer, ramen, and snow festival headline the urban side.',
    landscape_type: ['mountain', 'countryside', 'arctic'],
    activities: ['skiing', 'hiking', 'food', 'wildlife', 'photography'],
    cuisine_tags: ['japanese'],
    centroid_lat: 43.06,
    centroid_lon: 141.35,
    is_coastal: true,
  },
  {
    slug: 'jp-okinawa-main',
    name: 'Okinawa Main',
    country_code: 'JP',
    country_name: 'Japan',
    geojson_id: 'jp-okinawa-main',
    description:
      'A subtropical island chain with a distinct Ryukyuan culture, castle ruins, and coral reefs teeming with marine life. Okinawa\'s longevity diet, awamori spirit, and US military-base history give it a complex identity within Japan.',
    landscape_type: ['island', 'beach'],
    activities: ['diving', 'snorkeling', 'beach', 'cultural', 'food'],
    cuisine_tags: ['japanese'],
    centroid_lat: 26.33,
    centroid_lon: 127.8,
    is_coastal: true,
  },
  {
    slug: 'jp-miyako-yaeyama',
    name: 'Miyako-jima & Yaeyama',
    country_code: 'JP',
    country_name: 'Japan',
    geojson_id: 'jp-miyako-yaeyama',
    description:
      'Japan\'s far southern islands offer Caribbean-clear water and mangrove jungles closer to Taiwan than to Tokyo. Ishigaki, Iriomote, and Miyako-jima deliver some of the country\'s best beaches and least-crowded diving.',
    landscape_type: ['island', 'beach', 'jungle'],
    activities: ['diving', 'snorkeling', 'beach', 'kayaking', 'wildlife'],
    cuisine_tags: ['japanese'],
    centroid_lat: 24.4,
    centroid_lon: 124.2,
    is_coastal: true,
  },
  {
    slug: 'jp-alps',
    name: 'Japanese Alps',
    country_code: 'JP',
    country_name: 'Japan',
    geojson_id: 'jp-alps',
    description:
      'Three mountain ranges spanning central Honshu offer dramatic alpine scenery, onsen hot springs, and the beautifully preserved Edo-era post towns of Takayama, Shirakawa-go, and Matsumoto. The Tateyama-Kurobe Alpine Route is a seasonal spectacle.',
    landscape_type: ['mountain', 'countryside'],
    activities: ['hiking', 'skiing', 'cultural', 'food', 'photography'],
    cuisine_tags: ['japanese'],
    centroid_lat: 36.25,
    centroid_lon: 137.6,
    is_coastal: false,
  },

  // ─── Greece (6) ────────────────────────────────────────────────────
  {
    slug: 'gr-athens',
    name: 'Athens',
    country_code: 'GR',
    country_name: 'Greece',
    geojson_id: 'gr-athens',
    description:
      'The cradle of Western civilization pairs the Acropolis and ancient Agora with gritty street art, rooftop cocktail bars, and a revitalized food scene in neighborhoods like Psyrri and Exarcheia.',
    landscape_type: ['city'],
    activities: ['cultural', 'food', 'nightlife', 'photography'],
    cuisine_tags: ['greek'],
    centroid_lat: 37.98,
    centroid_lon: 23.73,
    is_coastal: true,
  },
  {
    slug: 'gr-cyclades',
    name: 'Cyclades',
    country_code: 'GR',
    country_name: 'Greece',
    geojson_id: 'gr-cyclades',
    description:
      'Whitewashed villages spill down volcanic cliffs above the Aegean on islands like Santorini, Mykonos, Naxos, and Paros. Each island has its own character -- from Santorini\'s caldera sunsets to Milos\' lunar beaches and Tinos\' marble artisanship.',
    landscape_type: ['island', 'beach'],
    activities: ['beach', 'cultural', 'food', 'photography', 'nightlife', 'snorkeling'],
    cuisine_tags: ['greek'],
    centroid_lat: 37.0,
    centroid_lon: 25.2,
    is_coastal: true,
  },
  {
    slug: 'gr-ionian',
    name: 'Ionian Islands',
    country_code: 'GR',
    country_name: 'Greece',
    geojson_id: 'gr-ionian',
    description:
      'Corfu, Kefalonia, and Zakynthos anchor Greece\'s western island chain, greener and lusher than the Aegean Cyclades. Venetian-era architecture, Navagio Beach\'s shipwreck cove, and pine-backed bays define the Ionian character.',
    landscape_type: ['island', 'beach', 'mountain'],
    activities: ['beach', 'snorkeling', 'kayaking', 'cultural', 'hiking'],
    cuisine_tags: ['greek'],
    centroid_lat: 38.7,
    centroid_lon: 20.7,
    is_coastal: true,
  },
  {
    slug: 'gr-crete',
    name: 'Crete',
    country_code: 'GR',
    country_name: 'Greece',
    geojson_id: 'gr-crete',
    description:
      'Greece\'s largest island spans Minoan palace ruins, the dramatic Samaria Gorge, and remote southern beaches accessible only by boat. Cretan cuisine -- built on olive oil, wild greens, and aged graviera cheese -- is considered the pinnacle of the Mediterranean diet.',
    landscape_type: ['island', 'beach', 'mountain'],
    activities: ['hiking', 'beach', 'cultural', 'food', 'snorkeling', 'photography'],
    cuisine_tags: ['greek'],
    centroid_lat: 35.24,
    centroid_lon: 24.9,
    is_coastal: true,
  },
  {
    slug: 'gr-dodecanese',
    name: 'Dodecanese',
    country_code: 'GR',
    country_name: 'Greece',
    geojson_id: 'gr-dodecanese',
    description:
      'Strung along Turkey\'s Aegean coast, the Dodecanese blend Greek and Ottoman heritage. Rhodes\' medieval old town is a UNESCO site, while tiny Symi, Patmos, and Kalymnos offer pastel harbors and world-class sport climbing.',
    landscape_type: ['island', 'beach'],
    activities: ['cultural', 'beach', 'climbing', 'snorkeling', 'photography'],
    cuisine_tags: ['greek'],
    centroid_lat: 36.4,
    centroid_lon: 27.1,
    is_coastal: true,
  },
  {
    slug: 'gr-northern',
    name: 'Northern Greece',
    country_code: 'GR',
    country_name: 'Greece',
    geojson_id: 'gr-northern',
    description:
      'Thessaloniki\'s Byzantine churches and waterfront promenade anchor a region that includes the monasteries of Meteora, the beaches of Halkidiki, and the forested slopes of Mt. Olympus. Less touristed than the islands, with arguably better food.',
    landscape_type: ['mountain', 'city', 'beach', 'countryside'],
    activities: ['cultural', 'hiking', 'food', 'beach', 'photography'],
    cuisine_tags: ['greek'],
    centroid_lat: 40.63,
    centroid_lon: 22.94,
    is_coastal: true,
  },

  // ─── Portugal (7) ──────────────────────────────────────────────────
  {
    slug: 'pt-lisbon',
    name: 'Lisbon',
    country_code: 'PT',
    country_name: 'Portugal',
    geojson_id: 'pt-lisbon',
    description:
      'Built on seven hills overlooking the Tagus estuary, Lisbon layers Moorish Alfama\'s fado clubs with the contemporary art of LX Factory and the pasteis de nata of Belem. Sintra\'s fairy-tale palaces are a quick train ride away.',
    landscape_type: ['city'],
    activities: ['food', 'cultural', 'nightlife', 'photography', 'surfing'],
    cuisine_tags: ['portuguese'],
    centroid_lat: 38.72,
    centroid_lon: -9.14,
    is_coastal: true,
  },
  {
    slug: 'pt-algarve',
    name: 'Algarve',
    country_code: 'PT',
    country_name: 'Portugal',
    geojson_id: 'pt-algarve',
    description:
      'Portugal\'s southern coast is defined by golden sea stacks, hidden coves, and year-round sunshine. Lagos, Faro, and the westernmost cliffs of Sagres blend surf culture with grilled-fish simplicity, drawing both package tourists and van-lifers.',
    landscape_type: ['beach', 'countryside'],
    activities: ['surfing', 'beach', 'kayaking', 'hiking', 'food', 'photography'],
    cuisine_tags: ['portuguese'],
    centroid_lat: 37.08,
    centroid_lon: -8.25,
    is_coastal: true,
  },
  {
    slug: 'pt-porto-douro',
    name: 'Porto & Douro',
    country_code: 'PT',
    country_name: 'Portugal',
    geojson_id: 'pt-porto-douro',
    description:
      'Stacked along the Douro River, Porto\'s tiled facades and port-wine cellars sit at the gateway to the world\'s oldest demarcated wine region. A river cruise or drive upstream reveals terraced vineyards carved into steep granite hillsides.',
    landscape_type: ['city', 'river', 'countryside'],
    activities: ['food', 'cultural', 'photography', 'cycling'],
    cuisine_tags: ['portuguese'],
    centroid_lat: 41.15,
    centroid_lon: -8.61,
    is_coastal: true,
  },
  {
    slug: 'pt-azores-sao-miguel',
    name: 'Azores Sao Miguel',
    country_code: 'PT',
    country_name: 'Portugal',
    geojson_id: 'pt-azores-sao-miguel',
    description:
      'The largest Azorean island features crater lakes ringed by hydrangeas, volcanic hot springs at Furnas, and some of Europe\'s best whale-watching. Lush green year-round, Sao Miguel is the accessible gateway to this mid-Atlantic archipelago.',
    landscape_type: ['island', 'mountain', 'countryside'],
    activities: ['hiking', 'wildlife', 'photography', 'kayaking', 'diving'],
    cuisine_tags: ['portuguese'],
    centroid_lat: 37.75,
    centroid_lon: -25.68,
    is_coastal: true,
  },
  {
    slug: 'pt-azores-pico-faial',
    name: 'Azores Pico & Faial',
    country_code: 'PT',
    country_name: 'Portugal',
    geojson_id: 'pt-azores-pico-faial',
    description:
      'Pico\'s volcanic cone is Portugal\'s highest point, rising above UNESCO-listed vineyards laid out in basalt-walled corrals. Neighboring Faial\'s marina at Horta is a legendary mid-Atlantic yachting stopover, and the channel between them is prime sperm-whale territory.',
    landscape_type: ['island', 'mountain'],
    activities: ['hiking', 'wildlife', 'diving', 'photography', 'climbing'],
    cuisine_tags: ['portuguese'],
    centroid_lat: 38.47,
    centroid_lon: -28.4,
    is_coastal: true,
  },
  {
    slug: 'pt-azores-flores',
    name: 'Azores Flores',
    country_code: 'PT',
    country_name: 'Portugal',
    geojson_id: 'pt-azores-flores',
    description:
      'The westernmost point of Europe, Flores is a tiny island of cascading waterfalls, deep caldeiras, and almost no tourists. Its isolation and raw volcanic beauty make it the most rewarding -- and hardest to reach -- of the Azores.',
    landscape_type: ['island', 'mountain'],
    activities: ['hiking', 'photography', 'wildlife', 'kayaking'],
    cuisine_tags: ['portuguese'],
    centroid_lat: 39.45,
    centroid_lon: -31.18,
    is_coastal: true,
  },
  {
    slug: 'pt-madeira',
    name: 'Madeira',
    country_code: 'PT',
    country_name: 'Portugal',
    geojson_id: 'pt-madeira',
    description:
      'A subtropical island of levada irrigation-channel walks, vertiginous sea cliffs, and year-round mild weather. Funchal\'s Old Town murals, Madeira wine lodges, and the ultra-dramatic Pico do Arieiro sunrise hike make it a four-season destination.',
    landscape_type: ['island', 'mountain'],
    activities: ['hiking', 'photography', 'food', 'diving', 'cycling'],
    cuisine_tags: ['portuguese'],
    centroid_lat: 32.65,
    centroid_lon: -16.91,
    is_coastal: true,
  },

  // ─── Morocco (4) ───────────────────────────────────────────────────
  {
    slug: 'ma-marrakech-atlas',
    name: 'Marrakech & Atlas',
    country_code: 'MA',
    country_name: 'Morocco',
    geojson_id: 'ma-marrakech-atlas',
    description:
      'Marrakech\'s Djemaa el-Fna square erupts nightly with storytellers, musicians, and food stalls, while the snow-capped High Atlas behind the city offers Berber villages and North Africa\'s highest peak, Jebel Toubkal.',
    landscape_type: ['city', 'mountain', 'desert'],
    activities: ['cultural', 'food', 'hiking', 'photography', 'adventure'],
    cuisine_tags: ['moroccan'],
    centroid_lat: 31.63,
    centroid_lon: -8.0,
    is_coastal: false,
  },
  {
    slug: 'ma-fes-imperial',
    name: 'Fes & Imperial Cities',
    country_code: 'MA',
    country_name: 'Morocco',
    geojson_id: 'ma-fes-imperial',
    description:
      'Fes el-Bali is the world\'s largest car-free urban area, a medieval medina of tanneries, mosques, and madrasas. Together with Meknes and Rabat, this region represents Morocco\'s imperial heritage and living craft traditions.',
    landscape_type: ['city', 'countryside'],
    activities: ['cultural', 'food', 'photography'],
    cuisine_tags: ['moroccan'],
    centroid_lat: 34.03,
    centroid_lon: -5.0,
    is_coastal: false,
  },
  {
    slug: 'ma-agadir-atlantic',
    name: 'Agadir & Atlantic',
    country_code: 'MA',
    country_name: 'Morocco',
    geojson_id: 'ma-agadir-atlantic',
    description:
      'Morocco\'s Atlantic coast stretches from the windsurfing hub of Essaouira to Agadir\'s wide sandy beach and the surf breaks of Taghazout. The coast blends Berber culture, argan-oil cooperatives, and laid-back beach-town vibes.',
    landscape_type: ['beach', 'desert'],
    activities: ['surfing', 'beach', 'food', 'cultural', 'photography'],
    cuisine_tags: ['moroccan'],
    centroid_lat: 30.42,
    centroid_lon: -9.6,
    is_coastal: true,
  },
  {
    slug: 'ma-sahara',
    name: 'Sahara (Merzouga)',
    country_code: 'MA',
    country_name: 'Morocco',
    geojson_id: 'ma-sahara',
    description:
      'The Erg Chebbi dunes near Merzouga deliver the quintessential Sahara experience: camel treks to desert camps, star-filled skies, and sunrise over golden sand seas. The Draa Valley and Todgha Gorge line the approach from Marrakech.',
    landscape_type: ['desert'],
    activities: ['adventure', 'photography', 'cultural', 'hiking'],
    cuisine_tags: ['moroccan'],
    centroid_lat: 31.1,
    centroid_lon: -4.01,
    is_coastal: false,
  },

  // ─── Sri Lanka (5) ─────────────────────────────────────────────────
  {
    slug: 'lk-colombo-west',
    name: 'Colombo & West Coast',
    country_code: 'LK',
    country_name: 'Sri Lanka',
    geojson_id: 'lk-colombo-west',
    description:
      'Sri Lanka\'s commercial capital mixes colonial Fort district architecture with the bustling Pettah market and an emerging restaurant scene. Negombo to the north offers a beach-town starting point near the international airport.',
    landscape_type: ['city', 'beach'],
    activities: ['food', 'cultural', 'nightlife', 'photography'],
    cuisine_tags: ['sri-lankan'],
    centroid_lat: 6.93,
    centroid_lon: 79.85,
    is_coastal: true,
  },
  {
    slug: 'lk-galle-south',
    name: 'Galle & South Coast',
    country_code: 'LK',
    country_name: 'Sri Lanka',
    geojson_id: 'lk-galle-south',
    description:
      'Galle Fort\'s Dutch-colonial ramparts overlook the Indian Ocean, while the southern coast from Unawatuna to Mirissa offers whale watching, stilt fishermen, and palm-fringed surf breaks. This stretch is Sri Lanka\'s most tourist-developed coastline.',
    landscape_type: ['beach', 'city'],
    activities: ['surfing', 'beach', 'wildlife', 'cultural', 'photography', 'diving'],
    cuisine_tags: ['sri-lankan'],
    centroid_lat: 6.03,
    centroid_lon: 80.22,
    is_coastal: true,
  },
  {
    slug: 'lk-kandy-hills',
    name: 'Kandy & Hills',
    country_code: 'LK',
    country_name: 'Sri Lanka',
    geojson_id: 'lk-kandy-hills',
    description:
      'The hill country around Kandy, Ella, and Nuwara Eliya delivers tea plantations, misty peaks, and the famous blue train ride. Kandy\'s Temple of the Tooth is Sri Lanka\'s most sacred Buddhist site.',
    landscape_type: ['mountain', 'countryside'],
    activities: ['hiking', 'cultural', 'photography', 'cycling', 'food'],
    cuisine_tags: ['sri-lankan'],
    centroid_lat: 7.29,
    centroid_lon: 80.64,
    is_coastal: false,
  },
  {
    slug: 'lk-trincomalee-east',
    name: 'Trincomalee & East',
    country_code: 'LK',
    country_name: 'Sri Lanka',
    geojson_id: 'lk-trincomalee-east',
    description:
      'Sri Lanka\'s east coast sees its dry season when the south is wet, offering uncrowded beaches at Nilaveli and Pasikuda, plus the surf town of Arugam Bay. Trincomalee\'s natural harbor and Pigeon Island snorkeling are highlights.',
    landscape_type: ['beach'],
    activities: ['surfing', 'beach', 'snorkeling', 'diving', 'wildlife'],
    cuisine_tags: ['sri-lankan'],
    centroid_lat: 8.57,
    centroid_lon: 81.23,
    is_coastal: true,
  },
  {
    slug: 'lk-yala',
    name: 'Yala Safari',
    country_code: 'LK',
    country_name: 'Sri Lanka',
    geojson_id: 'lk-yala',
    description:
      'Yala National Park has one of the highest leopard densities in the world, alongside elephants, sloth bears, and prolific birdlife. The adjacent Bundala wetlands and Kumana bird sanctuary extend the wildlife corridor along the southeast coast.',
    landscape_type: ['jungle', 'beach'],
    activities: ['safari', 'wildlife', 'photography'],
    cuisine_tags: ['sri-lankan'],
    centroid_lat: 6.37,
    centroid_lon: 81.52,
    is_coastal: true,
  },

  // ─── Maldives (1) ──────────────────────────────────────────────────
  {
    slug: 'mv-atolls',
    name: 'Maldives Atolls',
    country_code: 'MV',
    country_name: 'Maldives',
    geojson_id: 'MV',
    description:
      'A chain of 26 atolls scattered across the Indian Ocean, where overwater villas, house reefs, and manta-ray cleaning stations define the luxury beach holiday. Local island guesthouses have opened the Maldives to budget travelers since 2009.',
    landscape_type: ['island', 'beach'],
    activities: ['diving', 'snorkeling', 'beach', 'surfing', 'wildlife', 'photography'],
    cuisine_tags: ['maldivian'],
    centroid_lat: 3.2,
    centroid_lon: 73.22,
    is_coastal: true,
  },

  // ─── Egypt (4) ─────────────────────────────────────────────────────
  {
    slug: 'eg-cairo-nile',
    name: 'Cairo & Nile',
    country_code: 'EG',
    country_name: 'Egypt',
    geojson_id: 'eg-cairo-nile',
    description:
      'The Pyramids of Giza and the Grand Egyptian Museum anchor a chaotic, exhilarating megacity. Nile felucca rides, Khan el-Khalili bazaar, and Coptic Cairo offer layers of history spanning five millennia.',
    landscape_type: ['city', 'river', 'desert'],
    activities: ['cultural', 'food', 'photography'],
    cuisine_tags: ['egyptian'],
    centroid_lat: 30.04,
    centroid_lon: 31.24,
    is_coastal: false,
  },
  {
    slug: 'eg-red-sea',
    name: 'Red Sea Coast',
    country_code: 'EG',
    country_name: 'Egypt',
    geojson_id: 'eg-red-sea',
    description:
      'Hurghada and Marsa Alam line a coast with some of the world\'s most accessible coral reefs and warm, clear water year-round. Elphinstone Reef\'s oceanic whitetip sharks and the Brothers Islands attract advanced divers from around the globe.',
    landscape_type: ['beach', 'desert'],
    activities: ['diving', 'snorkeling', 'beach', 'wildlife', 'photography'],
    cuisine_tags: ['egyptian'],
    centroid_lat: 26.0,
    centroid_lon: 34.1,
    is_coastal: true,
  },
  {
    slug: 'eg-sinai',
    name: 'Sinai',
    country_code: 'EG',
    country_name: 'Egypt',
    geojson_id: 'eg-sinai',
    description:
      'The Sinai Peninsula bridges Africa and Asia with the coral-filled waters of Dahab and Sharm el-Sheikh, the desert canyons favored by Bedouin guides, and the pre-dawn climb of Mt. Sinai for sunrise over the biblical landscape.',
    landscape_type: ['desert', 'beach', 'mountain'],
    activities: ['diving', 'snorkeling', 'hiking', 'adventure', 'climbing', 'cultural'],
    cuisine_tags: ['egyptian'],
    centroid_lat: 28.5,
    centroid_lon: 33.85,
    is_coastal: true,
  },
  {
    slug: 'eg-luxor-upper',
    name: 'Luxor & Upper Egypt',
    country_code: 'EG',
    country_name: 'Egypt',
    geojson_id: 'eg-luxor-upper',
    description:
      'The Valley of the Kings, Karnak Temple, and the Colossi of Memnon line the Nile at Luxor, often called the world\'s greatest open-air museum. Multi-day Nile cruises between Luxor and Aswan pass Edfu and Kom Ombo temples.',
    landscape_type: ['desert', 'river'],
    activities: ['cultural', 'photography'],
    cuisine_tags: ['egyptian'],
    centroid_lat: 25.69,
    centroid_lon: 32.64,
    is_coastal: false,
  },

  // ─── South Africa (4) ──────────────────────────────────────────────
  {
    slug: 'za-cape-town',
    name: 'Cape Town & Western Cape',
    country_code: 'ZA',
    country_name: 'South Africa',
    geojson_id: 'za-cape-town',
    description:
      'Table Mountain frames a cosmopolitan city with world-class wine regions in Stellenbosch and Franschhoek, penguin colonies at Boulders Beach, and the dramatic Cape of Good Hope. The culinary scene rivals any global food capital.',
    landscape_type: ['city', 'mountain', 'beach', 'countryside'],
    activities: ['food', 'hiking', 'surfing', 'cultural', 'photography', 'wildlife', 'diving'],
    cuisine_tags: ['african'],
    centroid_lat: -33.93,
    centroid_lon: 18.42,
    is_coastal: true,
  },
  {
    slug: 'za-garden-route',
    name: 'Garden Route',
    country_code: 'ZA',
    country_name: 'South Africa',
    geojson_id: 'za-garden-route',
    description:
      'A 300-km stretch of coast from Mossel Bay to Storms River, where indigenous forest meets the Indian Ocean. Highlights include Tsitsikamma\'s suspension bridges, Knysna\'s lagoon, and the world\'s highest commercial bungee jump at Bloukrans.',
    landscape_type: ['beach', 'jungle', 'mountain'],
    activities: ['hiking', 'adventure', 'wildlife', 'kayaking', 'photography'],
    cuisine_tags: ['african'],
    centroid_lat: -33.95,
    centroid_lon: 23.0,
    is_coastal: true,
  },
  {
    slug: 'za-kruger',
    name: 'Kruger & Limpopo',
    country_code: 'ZA',
    country_name: 'South Africa',
    geojson_id: 'za-kruger',
    description:
      'One of Africa\'s largest game reserves, Kruger spans nearly two million hectares of savanna teeming with the Big Five. Self-drive safaris, private concessions, and the Panorama Route\'s Blyde River Canyon make this South Africa\'s premier wildlife destination.',
    landscape_type: ['jungle', 'countryside'],
    activities: ['safari', 'wildlife', 'photography', 'hiking'],
    cuisine_tags: ['african'],
    centroid_lat: -24.0,
    centroid_lon: 31.5,
    is_coastal: false,
  },
  {
    slug: 'za-durban-kzn',
    name: 'Durban & KZN',
    country_code: 'ZA',
    country_name: 'South Africa',
    geojson_id: 'za-durban-kzn',
    description:
      'Durban\'s Indian-influenced bunny chow, warm Mozambique Current beaches, and the Drakensberg mountain escarpment define KwaZulu-Natal. Hluhluwe-Imfolozi for rhinos and iSimangaliso Wetland Park for hippos and whale sharks extend the region\'s wild appeal.',
    landscape_type: ['beach', 'mountain', 'city'],
    activities: ['surfing', 'safari', 'wildlife', 'hiking', 'food', 'beach'],
    cuisine_tags: ['african'],
    centroid_lat: -29.86,
    centroid_lon: 31.03,
    is_coastal: true,
  },

  // ─── Tanzania (3) ──────────────────────────────────────────────────
  {
    slug: 'tz-zanzibar',
    name: 'Zanzibar',
    country_code: 'TZ',
    country_name: 'Tanzania',
    geojson_id: 'tz-zanzibar',
    description:
      'The Spice Island\'s Stone Town is a UNESCO-listed labyrinth of carved-door Arabic mansions and spice markets. Beyond the old town, white-sand beaches at Nungwi and Paje offer kite-surfing and dhow-sailing in warm turquoise waters.',
    landscape_type: ['island', 'beach'],
    activities: ['beach', 'cultural', 'snorkeling', 'diving', 'food', 'photography'],
    cuisine_tags: ['african'],
    centroid_lat: -6.16,
    centroid_lon: 39.19,
    is_coastal: true,
  },
  {
    slug: 'tz-serengeti',
    name: 'Serengeti & Northern Circuit',
    country_code: 'TZ',
    country_name: 'Tanzania',
    geojson_id: 'tz-serengeti',
    description:
      'The Great Migration of two million wildebeest and zebra defines the Serengeti, while Ngorongoro Crater\'s collapsed volcano shelters one of the densest concentrations of wildlife in Africa. Tarangire\'s baobab-studded elephant herds complete the northern circuit.',
    landscape_type: ['countryside'],
    activities: ['safari', 'wildlife', 'photography'],
    cuisine_tags: ['african'],
    centroid_lat: -2.33,
    centroid_lon: 34.83,
    is_coastal: false,
  },
  {
    slug: 'tz-kilimanjaro',
    name: 'Kilimanjaro',
    country_code: 'TZ',
    country_name: 'Tanzania',
    geojson_id: 'tz-kilimanjaro',
    description:
      'Africa\'s highest peak at 5,895 m is also the world\'s tallest free-standing mountain, climbable without technical gear via several multi-day routes. The surrounding coffee-growing Chagga communities and Arusha town serve as the staging ground.',
    landscape_type: ['mountain'],
    activities: ['hiking', 'climbing', 'photography', 'cultural'],
    cuisine_tags: ['african'],
    centroid_lat: -3.07,
    centroid_lon: 37.35,
    is_coastal: false,
  },

  // ─── Colombia (4) ──────────────────────────────────────────────────
  {
    slug: 'co-cartagena-caribbean',
    name: 'Cartagena & Caribbean',
    country_code: 'CO',
    country_name: 'Colombia',
    geojson_id: 'co-cartagena-caribbean',
    description:
      'Cartagena\'s walled colonial center bursts with bougainvillea, salsa music, and ceviche stands. The nearby Rosario Islands, Tayrona National Park, and Isla Baru extend the Caribbean coast with jungle-backed beaches and coral reefs.',
    landscape_type: ['city', 'beach', 'jungle'],
    activities: ['cultural', 'beach', 'diving', 'snorkeling', 'food', 'nightlife'],
    cuisine_tags: ['colombian'],
    centroid_lat: 10.39,
    centroid_lon: -75.51,
    is_coastal: true,
  },
  {
    slug: 'co-medellin-antioquia',
    name: 'Medellin & Antioquia',
    country_code: 'CO',
    country_name: 'Colombia',
    geojson_id: 'co-medellin-antioquia',
    description:
      'Once infamous, Medellin has reinvented itself with cable cars connecting hillside barrios, innovative public spaces, and a year-round spring climate at 1,500 m. Guatape\'s colorful lakeside town and Jardin\'s coffee fincas are popular weekend escapes.',
    landscape_type: ['city', 'mountain'],
    activities: ['cultural', 'nightlife', 'food', 'hiking', 'photography'],
    cuisine_tags: ['colombian'],
    centroid_lat: 6.25,
    centroid_lon: -75.57,
    is_coastal: false,
  },
  {
    slug: 'co-coffee-region',
    name: 'Coffee Region',
    country_code: 'CO',
    country_name: 'Colombia',
    geojson_id: 'co-coffee-region',
    description:
      'The Zona Cafetera around Salento, Filandia, and Manizales is a UNESCO Cultural Landscape where coffee fincas drape Andean hillsides. The Cocora Valley\'s towering wax palms -- Colombia\'s national tree -- create one of the country\'s most iconic landscapes.',
    landscape_type: ['mountain', 'countryside'],
    activities: ['hiking', 'cultural', 'food', 'photography', 'cycling'],
    cuisine_tags: ['colombian'],
    centroid_lat: 4.64,
    centroid_lon: -75.63,
    is_coastal: false,
  },
  {
    slug: 'co-bogota',
    name: 'Bogota',
    country_code: 'CO',
    country_name: 'Colombia',
    geojson_id: 'co-bogota',
    description:
      'Colombia\'s high-altitude capital blends the cobblestoned La Candelaria district with a booming gastronomy scene, the Gold Museum, and Monserrate\'s panoramic hilltop views. Cool and cosmopolitan at 2,640 m, Bogota is the cultural engine of the country.',
    landscape_type: ['city', 'mountain'],
    activities: ['cultural', 'food', 'nightlife', 'photography'],
    cuisine_tags: ['colombian'],
    centroid_lat: 4.71,
    centroid_lon: -74.07,
    is_coastal: false,
  },

  // ─── Mexico (5) ────────────────────────────────────────────────────
  {
    slug: 'mx-mexico-city',
    name: 'Mexico City',
    country_code: 'MX',
    country_name: 'Mexico',
    geojson_id: 'mx-mexico-city',
    description:
      'One of the world\'s great megacities, where Aztec ruins, Frida Kahlo\'s Blue House, and Michelin-starred restaurants coexist with vibrant street-food markets. Neighborhoods like Roma, Condesa, and Coyoacan each feel like a distinct city.',
    landscape_type: ['city'],
    activities: ['food', 'cultural', 'nightlife', 'photography'],
    cuisine_tags: ['mexican'],
    centroid_lat: 19.43,
    centroid_lon: -99.13,
    is_coastal: false,
  },
  {
    slug: 'mx-riviera-maya',
    name: 'Riviera Maya & Yucatan',
    country_code: 'MX',
    country_name: 'Mexico',
    geojson_id: 'mx-riviera-maya',
    description:
      'Cenote-dotted limestone jungle backs the Caribbean coast from Cancun to Tulum, with Chichen Itza and Uxmal\'s Maya pyramids inland. The region mixes resort beaches, reef diving, and ancient ruins in one compact corridor.',
    landscape_type: ['beach', 'jungle'],
    activities: ['diving', 'snorkeling', 'beach', 'cultural', 'adventure', 'nightlife'],
    cuisine_tags: ['mexican'],
    centroid_lat: 20.63,
    centroid_lon: -87.08,
    is_coastal: true,
  },
  {
    slug: 'mx-oaxaca',
    name: 'Oaxaca',
    country_code: 'MX',
    country_name: 'Mexico',
    geojson_id: 'mx-oaxaca',
    description:
      'Mexico\'s culinary and indigenous-arts capital, where mole sauces, mezcal distilleries, and Zapotec ruins at Monte Alban converge. The Pacific coast at Puerto Escondido and Mazunte adds world-class surfing and sea-turtle nesting beaches.',
    landscape_type: ['city', 'mountain', 'beach'],
    activities: ['food', 'cultural', 'surfing', 'photography', 'hiking'],
    cuisine_tags: ['mexican'],
    centroid_lat: 17.07,
    centroid_lon: -96.72,
    is_coastal: true,
  },
  {
    slug: 'mx-baja',
    name: 'Baja California',
    country_code: 'MX',
    country_name: 'Mexico',
    geojson_id: 'mx-baja',
    description:
      'A 1,200-km peninsula where the Pacific meets the Sea of Cortez, offering gray-whale encounters in Baja Sur, the wine country of Valle de Guadalupe, and some of Mexico\'s best fish tacos in Ensenada. Cabo\'s resort scene anchors the southern tip.',
    landscape_type: ['desert', 'beach'],
    activities: ['surfing', 'diving', 'wildlife', 'food', 'kayaking', 'photography'],
    cuisine_tags: ['mexican'],
    centroid_lat: 28.0,
    centroid_lon: -113.0,
    is_coastal: true,
  },
  {
    slug: 'mx-puerto-vallarta',
    name: 'Puerto Vallarta & Pacific',
    country_code: 'MX',
    country_name: 'Mexico',
    geojson_id: 'mx-puerto-vallarta',
    description:
      'Puerto Vallarta\'s malecon boardwalk, Sierra Madre jungle zip-lines, and the hidden beaches of the Marietas Islands make Mexico\'s Pacific coast a year-round draw. Sayulita and San Pancho offer a bohemian surf-village alternative to the resorts.',
    landscape_type: ['beach', 'jungle', 'mountain'],
    activities: ['surfing', 'beach', 'diving', 'adventure', 'food', 'nightlife'],
    cuisine_tags: ['mexican'],
    centroid_lat: 20.65,
    centroid_lon: -105.23,
    is_coastal: true,
  },

  // ─── Argentina (4) ─────────────────────────────────────────────────
  {
    slug: 'ar-buenos-aires',
    name: 'Buenos Aires',
    country_code: 'AR',
    country_name: 'Argentina',
    geojson_id: 'ar-buenos-aires',
    description:
      'Tango milongas, world-class steakhouses, and faded Art Nouveau grandeur define Argentina\'s capital. Each barrio -- from La Boca\'s colorful caminito to Palermo\'s leafy cafe scene -- has a distinct personality fueled by late nights and strong espresso.',
    landscape_type: ['city'],
    activities: ['food', 'cultural', 'nightlife', 'photography'],
    cuisine_tags: ['argentinian'],
    centroid_lat: -34.6,
    centroid_lon: -58.38,
    is_coastal: true,
  },
  {
    slug: 'ar-patagonia',
    name: 'Patagonia',
    country_code: 'AR',
    country_name: 'Argentina',
    geojson_id: 'ar-patagonia',
    description:
      'The southern wilderness of glaciers, granite spires, and wind-swept steppe spans from Perito Moreno\'s calving ice wall to the trekking mecca of El Chalten and the penguin colonies of Punta Tombo. Patagonia rewards those who brave its epic scale and weather.',
    landscape_type: ['mountain', 'arctic', 'countryside'],
    activities: ['hiking', 'photography', 'wildlife', 'climbing', 'kayaking'],
    cuisine_tags: ['argentinian'],
    centroid_lat: -49.3,
    centroid_lon: -73.0,
    is_coastal: false,
  },
  {
    slug: 'ar-mendoza',
    name: 'Mendoza Wine Country',
    country_code: 'AR',
    country_name: 'Argentina',
    geojson_id: 'ar-mendoza',
    description:
      'Argentina\'s wine capital sits at the foot of the Andes, producing the world\'s best Malbec across vineyards in Lujan de Cuyo and the Uco Valley. Beyond the bodegas, Aconcagua and whitewater rafting in the Mendoza River add altitude and adrenaline.',
    landscape_type: ['countryside', 'mountain'],
    activities: ['food', 'cycling', 'hiking', 'photography', 'adventure'],
    cuisine_tags: ['argentinian'],
    centroid_lat: -32.89,
    centroid_lon: -68.85,
    is_coastal: false,
  },
  {
    slug: 'ar-salta-northwest',
    name: 'Salta & Northwest',
    country_code: 'AR',
    country_name: 'Argentina',
    geojson_id: 'ar-salta-northwest',
    description:
      'Colonial Salta anchors Argentina\'s Andean northwest, where the Quebrada de Humahuaca\'s rainbow-striped hills, Salinas Grandes salt flats, and Cafayate\'s high-altitude Torrontes vineyards create some of South America\'s most dramatic road-trip scenery.',
    landscape_type: ['mountain', 'desert', 'countryside'],
    activities: ['hiking', 'photography', 'cultural', 'food', 'cycling'],
    cuisine_tags: ['argentinian'],
    centroid_lat: -24.79,
    centroid_lon: -65.41,
    is_coastal: false,
  },

  // ─── Iceland (3) ───────────────────────────────────────────────────
  {
    slug: 'is-reykjavik-south',
    name: 'Reykjavik & South Coast',
    country_code: 'IS',
    country_name: 'Iceland',
    geojson_id: 'is-reykjavik-south',
    description:
      'Iceland\'s compact capital pairs a thriving coffee and music scene with easy access to the Golden Circle, black-sand beaches at Vik, and the glacier lagoon at Jokulsarlon. The south coast packs waterfalls, ice caves, and volcanic landscapes into one iconic drive.',
    landscape_type: ['arctic', 'mountain', 'beach'],
    activities: ['hiking', 'photography', 'adventure', 'wildlife', 'cultural'],
    cuisine_tags: ['icelandic'],
    centroid_lat: 64.15,
    centroid_lon: -21.94,
    is_coastal: true,
  },
  {
    slug: 'is-north',
    name: 'North Iceland',
    country_code: 'IS',
    country_name: 'Iceland',
    geojson_id: 'is-north',
    description:
      'Akureyri is the gateway to Husavik\'s whale watching, the Myvatn volcanic region\'s craters and hot springs, and Dettifoss, Europe\'s most powerful waterfall. The diamond circle rivals the south coast with fewer crowds.',
    landscape_type: ['arctic', 'mountain'],
    activities: ['wildlife', 'hiking', 'photography', 'adventure'],
    cuisine_tags: ['icelandic'],
    centroid_lat: 65.68,
    centroid_lon: -18.09,
    is_coastal: true,
  },
  {
    slug: 'is-westfjords',
    name: 'Westfjords',
    country_code: 'IS',
    country_name: 'Iceland',
    geojson_id: 'is-westfjords',
    description:
      'Iceland\'s most remote region, where dramatic fjords, towering Latrabjarg bird cliffs, and natural hot pots exist without crowds. Accessible only via winding gravel roads, the Westfjords reward those who make the journey with raw, unfiltered Iceland.',
    landscape_type: ['arctic', 'mountain'],
    activities: ['hiking', 'wildlife', 'photography', 'kayaking'],
    cuisine_tags: ['icelandic'],
    centroid_lat: 65.75,
    centroid_lon: -22.7,
    is_coastal: true,
  },

  // ─── Norway (4) ────────────────────────────────────────────────────
  {
    slug: 'no-oslo-east',
    name: 'Oslo & Eastern Norway',
    country_code: 'NO',
    country_name: 'Norway',
    geojson_id: 'no-oslo-east',
    description:
      'Norway\'s capital has reinvented its waterfront with the Munch Museum, the Oslo Opera House, and Aker Brygge\'s dining promenade. The surrounding Oslofjord and forests of Nordmarka offer quick escapes into nature year-round.',
    landscape_type: ['city', 'countryside'],
    activities: ['cultural', 'food', 'hiking', 'skiing', 'photography'],
    cuisine_tags: ['norwegian'],
    centroid_lat: 59.91,
    centroid_lon: 10.75,
    is_coastal: true,
  },
  {
    slug: 'no-bergen-fjords',
    name: 'Bergen & Fjords',
    country_code: 'NO',
    country_name: 'Norway',
    geojson_id: 'no-bergen-fjords',
    description:
      'Bergen\'s colorful Bryggen wharf is the gateway to the Norwegian fjords, including Sognefjorden and Hardangerfjorden. Preikestolen (Pulpit Rock) and Trolltunga rank among Norway\'s most iconic viewpoints, accessible via multi-hour hikes.',
    landscape_type: ['mountain', 'river', 'city'],
    activities: ['hiking', 'kayaking', 'photography', 'cultural', 'food'],
    cuisine_tags: ['norwegian'],
    centroid_lat: 60.39,
    centroid_lon: 5.32,
    is_coastal: true,
  },
  {
    slug: 'no-lofoten',
    name: 'Lofoten Islands',
    country_code: 'NO',
    country_name: 'Norway',
    geojson_id: 'no-lofoten',
    description:
      'Jagged peaks rise from the Norwegian Sea above red-painted rorbu fishing cabins, creating one of the world\'s most photogenic archipelagos. Midnight sun in summer, northern lights in winter, and year-round surfing in Arctic waters set Lofoten apart.',
    landscape_type: ['island', 'mountain', 'arctic'],
    activities: ['hiking', 'photography', 'surfing', 'kayaking', 'fishing'],
    cuisine_tags: ['norwegian'],
    centroid_lat: 68.23,
    centroid_lon: 14.56,
    is_coastal: true,
  },
  {
    slug: 'no-tromso-arctic',
    name: 'Tromso & Arctic North',
    country_code: 'NO',
    country_name: 'Norway',
    geojson_id: 'no-tromso-arctic',
    description:
      'The "Gateway to the Arctic" is the best city in Norway for northern-lights viewing, dog-sledding, and Sami cultural encounters. Tromso\'s Arctic Cathedral and lively bar scene belie its latitude above 69 degrees north.',
    landscape_type: ['arctic', 'mountain', 'city'],
    activities: ['wildlife', 'photography', 'skiing', 'hiking', 'cultural', 'adventure'],
    cuisine_tags: ['norwegian'],
    centroid_lat: 69.65,
    centroid_lon: 18.96,
    is_coastal: true,
  },
];
